### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by JosephDuffy**
This is a copy/paste from https://github.com/JosephDuffy/Persist/, with a couple of small tweaks:

- Only tests iOS; macOS, tvOS, and watchOS were removed
- Coverage is not uploaded to Codecov; I don't have permission to add the project
- Xcode 11.5 is used; this is the latest stable version
- v2 of the cache action is used; this is the latest stable version

It will do the following:

- Perform a release when a tag starting with `v` is pushed
  - `v0*` or `v*-` (e.g. `v1.1.0-rc1`) will be marked as pre-release
- Build and upload docs to the `gh-pages` branch as part of releases
- Run tests against iOS when a commit is pushed

Note that the cache is not as useful as it could be right now; Swift likes to rebuild things based on inodes so the cache is largely (maybe entirely) discarded, but will be useful in a future Swift release.

You'll need to [create an orphaned `gh-pages` branch](https://www.scivision.dev/create-blank-orphan-git-branch-gh-pages/) for the docs since I don't have permissions. I don't think it needs an initial commit, although maybe you can't push an empty branch? I've never tried.

### CODE REVIEW

**Comment by JosephDuffy** [comment]
Currently the tests are failing because `MockDelegate` and `MockSectionProviderMappingDelegate` do not conform to `SectionProviderUpdateDelegate` and `SectionProviderMappingDelegate` respectively. Looks like this is a breaking API change.

**Comment by shaps80** [comment]
Hey I love this. I will fix the tests but I think this is a great inclusion.

**Comment by shaps80** [comment]
Hmm looks like the tests are passing for me, because they do in fact conform to the right protocols. I thought I had fixed them. I must have done this since Jul when you raised that point 👍

**Comment by shaps80** [comment]
So I'd like to merge this but I have one preference. I don't like using prefixes like `v1.0` I'm happier with just `1.0` or wateva. Also I never create tags on my OSS projects unless its a release, so if you can just fix that, I'm happy to merge.

Once we merge, do we need to do anything else or does it 'just work'? I'm happy to give you access to the repo if you need to finish the configuration on this end.

**Comment by JosephDuffy** [comment]
> So I'd like to merge this but I have one preference. I don't like using prefixes like `v1.0` I'm happier with just `1.0` or wateva.

The `v` can be dropped from the tags but then you would have to decide on the pattern for what tags trigger a release. e.g. Anything that has a `.` in it, anything that starts with a number, any tag at all?

> Also I never create tags on my OSS projects unless its a release, so if you can just fix that, I'm happy to merge.

The tests run on any push to any branch so they'll run automatically and you'll only need to create a tag when there's a release.

> Once we merge, do we need to do anything else or does it 'just work'?

The tests will "just work" on every push _to this repo_ but I believe by default they don't run on PRs from forks, which it looks like [they added either this month](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).

> I'm happy to give you access to the repo if you need to finish the configuration on this end.

If you wanted things like Codecov down the line I would need access (or for you to do it). If I had access I would delete my forks and work directly on branches in these repos which might be easier.

**Comment by shaps80** [comment]
> The `v` can be dropped from the tags but then you would have to decide on the pattern for what tags trigger a release. e.g. Anything that has a `.` in it, anything that starts with a number, any tag at all?

Yeah I think any tag at all. If I tag, it's a release.

> The tests run on any push to any branch so they'll run automatically and you'll only need to create a tag when there's a release.

Sounds great!

> If you wanted things like Codecov down the line I would need access (or for you to do it). If I had access I would delete my forks and work directly on branches in these repos which might be easier.

Yeah let's add you as a contributor – I'll start generating PRs as well so we go through a proper review process. But if I feel like I'm holding you back, I'll happily allow you to move forward and unblock you.

**Comment by JosephDuffy** [comment]
Looks to all be passing (https://github.com/JosephDuffy/Composed-1/actions/runs/224341034), I think this is good to go?

**Review by shaps80 — APPROVED** [review]
Perfect, so is this ready to merge?

**Pull request merged**
